### ISSUE TITLE
ModuleNotFoundError: No module named 'sql_pgvector'

### ISSUE THREAD

**Issue by quartermaine** [langchain-ai/langserve#603]
I am trying to run langserve package from my  VSCode but I am getting the following error

![image](https://github.com/langchain-ai/langserve/assets/24212117/3b277084-f07c-45eb-b8d6-652f4540b5d6)

here is my file structure

![image](https://github.com/langchain-ai/langserve/assets/24212117/fae75ad3-9fa4-4b4b-8ba2-080f5a0817e4)

and the service.py file where I am trying to import the module

![image](https://github.com/langchain-ai/langserve/assets/24212117/b74357f1-9c13-4eac-9e99-4e42c26fca0b)

I am running 'langchain serve' command while I am on the my-app directory. Also I have created a settings.json file in the .vscode with the following content

`{
"python.analysis.extraPaths": [
    "./Artificial Intelligence/LLMs/LANGSERVE/my-app/packages/sql-pgvector"]
}`

**Comment by eyurtsev** [comment]
@quartermaine there's a poetry file at the root of the project.

It has a section that specifies the dependencies for the project. It'll look something like this

```toml
[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.23.2"
langserve = {extras = ["server"], version = ">=0.0.30"}
pydantic = "<2"
sqlvector = {path = "packages/sqlvector", develop = true}
```

Use pyproject to install the dependencies so that the package is added to your python path (or add it yourself).

Or else use vscode with poetry to have it install the environment properly
